# Makefile for Writing Make Files Example

# *****************************************************
# Variables to control Makefile operation

#CXX = gcc
#CXXFLAGS = -Wall -g -lm -lstdc++
CC=gcc
CFLAGS= -g -Wall -lm -lstdc++
# ****************************************************
# Targets needed to bring the executable up to date

#h1d:
#	$(CXX) $(CXXFLAGS) h1d.cpp -o h1d
h1d: h1d.cpp
# The main.o target can be written more simply
#gen: gen.cpp
test: test.cpp
