# Makefile for Writing Make Files Example

# *****************************************************
# Variables to control Makefile operation

#CXX = gcc
#CXXFLAGS = -Wall -g -lm -lstdc++
CC=gcc
CFLAGS= -g -Wall -lm -lstdc++
# ****************************************************
# Targets needed to bring the executable up to date

#h1a:
#	$(CXX) $(CXXFLAGS) h1a.cpp -o h1a
h1a: h1a.cpp
# The main.o target can be written more simply

